services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: mysql-native
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql:Z
